server:
  port: 8090
spring:
  application:
    name: loginserver  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 47.94.193.104:8848 #注册中心地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.193.104:3306/db_carhome?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

carhome:
  user:
    aeskey: 4PYuvnRVDaKE7E1feqq0FQ==