server:
  port: 8081 #自定义配置文件
spring:
  application:
    name: server  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 47.94.193.104:8848  #注册中心地
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.193.104:3306/db_openapi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

open:
  pass:
    pubkey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi8RDIhKYZDFv4FEfP7y3Zi60gcXyaPHx2c63GZcGy0bkUMZbIgB/+WNGZfgWR3XSeEclvA2hrf+RFrKncGImw39g0hyY1Xm3kXYaLqREGmhAdS6SJodQCLHJhfFz/GUYjOOnsa2JWaNzkkPPXQt6NlQ5BKFcwWHcQIMHbovLo0JwzZYEMfgrAflDzoCaqHSjmQArKGAN6Lg2K31M1BM9+Nv2rWZnzIo0j9+ZDF4jdC3/ZlnB42taB5RUJqRHgSzXjtigTJGFMPahiit4R0/WAnSpQHHQ4Xp/d4gFuLl8jCxpLePrsdETcnnYGmpL1Mm+rmyWyGIIm7XZ/bdatXHWbwIDAQAB
    prikey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCLxEMiEphkMW/gUR8/vLdmLrSBxfJo8fHZzrcZlwbLRuRQxlsiAH/5Y0Zl+BZHddJ4RyW8DaGt/5EWsqdwYibDf2DSHJjVebeRdhoupEQaaEB1LpImh1AIscmF8XP8ZRiM46exrYlZo3OSQ89dC3o2VDkEoVzBYdxAgwdui8ujQnDNlgQx+CsB+UPOgJqodKOZACsoYA3ouDYrfUzUEz342/atZmfMijSP35kMXiN0Lf9mWcHja1oHlFQmpEeBLNeO2KBMkYUw9qGKK3hHT9YCdKlAcdDhen93iAW4uXyMLGkt4+ux0RNyedgaakvUyb6ubJbIYgibtdn9t1q1cdZvAgMBAAECggEAcXZzlW6JHhVwICda+fAm5qIV0aAziXSYhNwmknSjhFRZtyVACFtliLxKAy+iToLcyN3hSUe7sDhfvZBtE3PqyhxXKlsiy3KTTlgVKzYZP2LQqRCUfwisNVK3KbB5GzWq9308vqYFcaqagOvhpERUA1TeMN8aILdkCU8Vsm10dGSbXfmL5dRMiYFF44TeiL+hlPnd0o/pbm6eOPe/wH2WWlSE5vIlZAOcOt8jO9X3Xzd+3iElMQ3RIycgQdvT2J68VYVpy4QdtIMM8gfYmhKASBHxmb58SEkQIZ5Gp+lGWxBeRWm6r5P/x1wSO284wI4AdUClTyKbYRq9O73QlZ0s0QKBgQDmxtFBCSBXi99j0wBQiEgu+7v/1Q9VRBDn8li0VrFzDA0HjmVAyIzgRQoQCmw9QPsOzAkYjqCuPAgTfMlP1imphjidEtKE8bHUJIwWPxZf3zqSs6sbGy3MEr+aTU0NGMyGTu1wb2XsmNJm3h9beuQfy+5tALuyRbtrmUb0f49R6QKBgQCbCvcB4QbQ3mWYfsCs6bVkS3MlvKfWk1JDonBVhzcx5uGAZAO3J+ZT8FGAAUK8WybSzPHAtemEseUl2jpAVn23XqLui4NDDPLU8juZNELcqLQ5/qzIv5wPIGfk9/OJ48EngIqrMpC5neNP69j57XmLLeqpLVPSnsKlmaM74lqWlwKBgGPnP+EqpUChAaUCTAmQ5cbJHXrD7m5YGAWBSVtQiGMonV9fCoBAEZRo7tFA4dimj8i5FVr3K6IhxNFC3RddvA1yWIHPCymYRAZ1h9t9lh8M0Rt/Ahyq6GmG2EFhI3D/AlNGSc25u+LvyW3UzLhae/Uz4FR508d6HoeXBDuGGTI5AoGASXyV/T8CcwemkfQqMQsJHgOhDVbxGoRzbnlU00UmxTFQ2wEMvchcpJZ4mrp+PjbaHPpk79mJWIrVOO7Jw2r7ZWmmwng//AzsIEC8PO6Hbn1MB10N2ozvVEAg3mcj+MyJ5cZIc8Kg1EngzyXTjwqfHHfkDNHeNCtpyQIcW6r7EvsCgYBeOANYD2LZHcR3Gr0EGQLtFgRCtWBFNkV9dKFsiHOj6CxZb4pSAAyXukMzMMZeKXu4Nda7kfNUXzzcVOZHS3E2jXigkERE8Or6XGhhX36OybLqqGfFx7S1+Ej1tNNbwCaISjaH1tRg+kFegNLuNgrWnNgoNF7IGV57gKUQBsK47w==