server:
  port: 8091
spring:
  application:
    name: mailserver  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 47.94.193.104:8848 #注册中心地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.193.104:3306/db_carhome?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

feign:
  client:
    config:
      default:
        connectTimeout: 20000 #设置连接的超时时间
        readTimeout: 30000  #设置读取的超时时间